server {
    listen       80;
    server_name  msfz.jy-admin.site;


    ssl_certificate     /etc/nginx/certs/msfz.jy-admin.site_bundle.crt;
    ssl_certificate_key /etc/nginx/certs/msfz.jy-admin.site.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    
    # 前端静态资源根目录
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location = / {
        return 302 /msfz/;
    }

    # 对于前端 SPA 静态资源，正常返回
    location /msfz/ {
        try_files $uri $uri/ /msfz/index.html;
    }
   

    # 一些常见的静态资源可加长缓存
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri /index.html;
    }

    # 简单的错误页
    error_page 404 /index.html;
}

